spec:
  name: cv-engine
  region: fra
  services:
    - name: frontend
      source_dir: frontend
      run_command: npm run start
      build_command: npm install && npm run build
      http_port: 3000
      envs:
        - key: NEXT_PUBLIC_API_URL
          value: "https://backend-<autogen>.ondigitalocean.app"

    - name: backend
      source_dir: backend
      dockerfile_path: backend/Dockerfile
      http_port: 8000
      envs:
        - key: OPENAI_API_KEY
          type: SECRET
